[workspace]
authors = ["WardDeb <w@rddeboutte.com>"]
channels = ["conda-forge", "bioconda"]
name = "deeptools25"
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
python = "3.12.*"
clang = "*"
libclang = "*"
perl = "*"
sra-tools = "*"
samtools = "*"
methyldackel = "*"
wiggletools = "*"
ucsc-wigtobigwig = "*"
uropa = "*"
pandas = "*"
r-tidyr = "*"
r-dplyr = "*"
bioconductor-deseq2 = "*"
subread = "*"
pip = "*"
macs3 = "*"

[pypi-dependencies]
snakemake = "== 9.9"
snakemake-storage-plugin-zenodo = "*"
snakemake-executor-plugin-cluster-generic = "*"
snakemake-executor-plugin-slurm = "*"
deeptools = { git = "https://github.com/deeptools/deepTools.git", rev = "benchmarking_4.0.0" }

[activation.env]
LIBCLANG_PATH = "$CONDA_PREFIX/lib"
CFLAGS = "-I$CONDA_PREFIX/include"

