restart-times: 3
local-cores: 1
latency-wait: 90
use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
jobs: 10
max-jobs-per-second: 1
max-status-checks-per-second: 2
executor: slurm
default-resources:
  slurm_partition: general
  cpus: 64
set-resources:
  bamCoverage1:
    runtime: 1h
    mem: 5GB * attempt
  bamCoverage2:
    runtime: 1h
    mem: 10GB * attempt
  bamCompare1:
    runtime: 1h
    mem: 8GB * attempt
  bamCompare2:
    runtime: 1h
    mem: 16GB * attempt
  computeMatrix1:
    runtime: 5h
    mem: 32GB * attempt
  computeMatrix2:
    runtime: 2h
    mem: 48GB * attempt
  multiBamSummary1:
    runtime: 5h
    mem: 32GB * attempt
  multiBamSummary2:
    runtime: 2h
    mem: 48GB * attempt
