restart-times: 5
local-cores: 1
latency-wait: 90
use-conda: True
jobs: 6
keep-going: True
rerun-incomplete: True
printshellcmds: True
max-jobs-per-second: 1
max-status-checks-per-second: 5
executor: slurm
default-resources:
  slurm_partition: general
  runtime: 30
  cpus: 32
set-resources:
  bamCoverage1:
    runtime: 1h
    mem: 5GB * attempt
  bamCoverage2:
    mem: 10GB * attempt
  bamCompare1:
    runtime: 1h
    mem: 10GB * attempt
  bamCompare2:
    mem: 10GB * attempt
  computeMatrix1:
    runtime: 2h
    mem: 10GB * attempt
  computeMatrix2:
    runtime: 2h
    mem: 15GB * attempt
  multiBamSummary1:
    runtime: 2h
    mem: 10GB * attempt
  multiBamSummary2:
    runtime: 2h
    mem: 20GB * attempt
