use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True

jobs: 10
max-jobs-per-second: 1
max-status-checks-per-second: 2
restart-times: 2

max-inventory-time: 600
latency-wait: 1200
wait-for-files:
  - zenodo/triticum_chip_SRR1686799.bam
  - zenodo/bigwigs/human_chip_SRR28592125.bw
  - zenodo/bigwigs/human_rna_SRR28012905.bw
  - zenodo/bigwigs/human_rna_SRR28012904.bw
  - zenodo/bigwigs/human_chip_SRR28592124.bw
  - zenodo/bigwigs/human_rna_SRR28012902.bw
  - zenodo/bigwigs/human_chip_SRR28592132.bw
  - zenodo/bigwigs/human_wgs_SRR15494527.bw
  - zenodo/bigwigs/human_chip_SRR28592131.bw
  - zenodo/bigwigs/human_rna_SRR28012903.bw
  - zenodo/triticum_chip_SRR1686799.bam.csi
  - zenodo/triticum_chip_SRR1686799_reverse.bw
  - zenodo/triticum_chip_SRR1686799_markdup.bw
  - zenodo/triticum_chip_SRR1686799_nodup.bw
  - zenodo/human_rna_SRR28012902.bam.bai
  - zenodo/human_rna_SRR28012902.bam
  - zenodo/triticum_rna_SRR27822150.bam
  - zenodo/triticum_rna_SRR27822150.bam.csi
  - zenodo/triticum_chip_SRR1686799_mapq10.bw
  - zenodo/human_chip_SRR28592124.bam
  - zenodo/triticum_wgs_SRR27887047.bam.csi
  - zenodo/human_wgs_SRR15494527.bam
  - zenodo/human_chip_SRR28592124.bam.bai
  - zenodo/triticum_chip_SRR1686799_fw.bw
  - zenodo/human_wgs_SRR15494527.bam.bai
  - zenodo/triticum_wgs_SRR27887047.bam

executor: slurm

default-resources:
  slurm_partition: general
  cpus: 144
  runtime: 24h

set-resources:
  bamCoverage1:
    mem: 32GB
  bamCoverage2:
    mem: 64GB
  bamCompare1:
    mem: 32GB
  bamCompare2:
    mem: 64GB
  computeMatrix1:
    mem: 32GB
  computeMatrix2:
    mem: 64GB
  multiBamSummary1:
    mem: 32GB
  multiBamSummary2:
    mem: 64GB
  process_results:
    runtime: 30
    mem: 4GB
