use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
jobs: 30
max-jobs-per-second: 1
max-status-checks-per-second: 2
restart-times: 2
max-inventory-time: 600
latency-wait: 1200
executor: slurm
