name: plot_benchmark
on:
  push:
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: conda-incubator/setup-miniconda@v3
            with:
              auto-update-conda: true
              environment-file: conf/env.yml
          - name: pip
            run: |
              CFLAGS=-I/$CONDA_PREFIX/include LIBCLANG_PATH=$CONDA_PREFIX/lib pip install -r conf/requirements.txt
