name: plot_benchmark
on:
  push:
  pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
                python-version: '3.13'
                cache: 'pip'
          - name: install
            run: |
              pip install -r .github/reqs_plotting.txt
          - name: plot
            run: |
              python scripts/plot_benchmark.py -i results/benchmark_results.csv -o benchmark.svg
          - uses: actions/upload-artifact@v4
            with:
              name: benchmark_plot
              path: benchmark.svg
